### ISSUE TITLE
Spaces in Hashtags

### ISSUE THREAD

**Issue by vmitchell85** [larastream/internals#43]
It's possible to have a space in a tag... probably shouldn't be able to do that.

![image](https://user-images.githubusercontent.com/1248035/36694942-caeddf00-1b0d-11e8-9f50-d6bdefc633c1.png)

**Comment by MatthewSH** [comment]
Maybe they need to convert to `-` instead? That was my bad. So instead of `#user requests` it would be `#user-requests`

**Comment by larastream** [comment]
Yeah, they need to be converted to have a hyphen. Tags are comma separated which is why the spaces are technically able to be present. I'll get that updated.

**Comment by larastream** [comment]
Issue is now resolved.
