### ISSUE TITLE
hashtags (css style)

### ISSUE THREAD

**Issue by ghost** [larastream/internals#45]
I've watched the latest stream of Jordan to the hashtags and afterwards I've looked on the explore page. There I've seen when the hashtags going into a second line that they will be cutted, even if they are split in two words. Maybe it would be nicer, when they will be not cutted.

Examples are Zlinto, OpenSource, sweetalert2, package, #php (as output), user requests

**Comment by MatthewSH** [comment]
I think the update only applies to new streams.

**Comment by JordanDalton** [comment]
There's not too much I can do about them wrapping.
