### ISSUE TITLE
URL _blank

### ISSUE THREAD

**Issue by Diddyy** [larastream/internals#54]
I believe any external URL's on the site should open using _blank so that it opens in another tab. It would currently open in the same tab taking me away from Larastreams, which not only is annoying but implementing this would help to keep visitors on the site.

An example that I have seen so far is links in a member's bio. But it would be wise to apply this to all links that are external?

**Comment by JordanDalton** [comment]
I agree. I use some package that converts markdown to html. I'll see what I can do to make non larastream urls open in different tab/window

**Comment by JordanDalton** [comment]
Done
